---
# HassMediaPrevious - default
# example: précédent
# context_area: true

language: fr
data:
  - sentences:
      - "précédent[e]"
      - "<media> précédent[e]"
      - "<mets> (<le>|au |à la )<media> précédent[e]"
    example: "précédent"
    response: "default"
  - sentences:
      - "morceau précédent"
      - "mets le morceau précédent"
    example: "morceau précédent"
    response: "default"
    speech_to_phrase: true
