---
# HassTimerStatus - default

language: "fi"
data:
  - sentences:
      - "[mikä on] (ajastimen|ajastuksen|ajastimien|ajastuksien) [jäljellä oleva] (tila|tilanne|aika|status)"
      - "(paljonko|kauanko|kuinka kauan|kuinka paljon) (aikaa on jäljellä|on aikaa jäljellä|on jäljellä|jäljellä aikaa|jäljellä) [minun|mun] (ajastimessa|ajastuksessa|ajastimissa|ajastuksissa)[ni]"
      - "jäljellä oleva aika [minun|mun] (ajastimessa|ajastuksessa|ajastimissa|ajastuksissa)[ni]"
    example: "ajastimen tila"
    response: "default"
