---
language: "ne"
data:
  - sentences:
      - "[मेरो] टाइमर[हरू]को <state_word> के (छ|छन्|छन)"
      - "[मेरो] टाइमर[हरू] कति बाँकी (छ|छन्|छन)"
      - "[मेरो] टाइमर[हरू]मा कति समय बाँकी (छ|छन्|छन)"
    example: "टाइमरको अवस्था के छ"
    response: "default"
