---
# HassTimerStatus - default
# example: stav časovače

language: "cs"
data:
  - sentences:
      - "stav <casovac>"
      - "kolik (zbývá;času) [na] <casovac>"
      - "[[jaký je] zbývající] čas <casovac>"
    example: "stav časovače"
    response: "default"
