language: sk
data:
  - sentences:
      - "(ahoj|čau) [home assistant]"
    example: "ahoj"
    response: hello
  - sentences:
      - "počúvaš stále"
    example: "počúvaš stále"
    response: listening
  - sentences:
      - "kam (idú|sa posielajú) moje dáta"
    example: "kam idú moje dáta"
    response: data
  - sentences:
      - "čo ti môžem povedať"
      - "čo ti môžem (pri|roz)kázať"
      - "čo sa [ťa] môžem [s|o]pýtať"
    example: "čo ti môžem povedať"
    response: commands
  - sentences:
      - "kto ťa vytvoril"
    example: "kto ťa vytvoril"
    response: creator
