---
# HassNevermind - default

language: "nl"
data:
  - sentences:
      - "laat maar [zitten]"
      - "annuleer"
    example: "laat maar zitten"
    response: "default"
  - sentences:
      - "laat maar zitten"
      - "annuleer"
    example: "laat maar zitten"
    response: "default"
    speech_to_phrase: true
