---
# HassCancelAllTimers - default
# example: cancel all timers

language: "sk"
data:
  - sentences:
      - "<timer_cancel> <all> <timer_type>"
    example: "cancel all timers"
    response: "default"
