---
# HassMediaPlayerUnmute - default
# example: включи звук
# context_area: true

language: "ru"
data:
  - sentences:
      - "(включи|верни) звук"
    example: "включи звук"
    response: "default"
