---
# HassMediaSearchAndPlay - default
# example: spiele Diese Drombuschs
# slots: {search_query}; context_area: true

language: de
data:
  - sentences:
      - "spiel[e][ <hier>] {search_query}[ ab]"
      - "spiel[e] {search_query} <hier>[ ab]"
      - "[<hier> ]{search_query} <starten_end_of_sentence>"
      - "{search_query} <hier> <starten_end_of_sentence>"
    example: spiele Diese Drombuschs
    response: default
