---
# HassGetCurrentDate - default
# example: what is the date

language: "sv"
data:
  - sentences:
      - "(<vad>) (datum|dag) [(idag|i dag)]"
    example: "vilket datum är det"
    response: "default"
