repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        args: ["--log-level", "debug"]
        types_or: [yaml]
  - repo: local
    hooks:
      - id: format
        name: Format
        entry: script/format
        language: python
