---
language: "th"
data:
  - sentences:
      - "[<polite_prefix>]เปิดเสียง[<polite_suffix>]"
      - "[<polite_prefix>]เปิดเสียง(เพลง|สื่อ)[<here>][<polite_suffix>]"
    example: "เปิดเสียง"
    response: "default"
