---
# HassNevermind - default
# example: nevermind

language: "en"
data:
  - sentences:
      - "nevermind"
      - "never mind"
    example: "nevermind"
    response: "default"
    speech_to_phrase: true
