---
# HassClimateGetTemperature - default
# example: what is the temperature
# context_area: true

language: "th"
data:
  - sentences:
      - "[ตอนนี้]อุณหภูมิ[<here>]เท่า(ไร|ไหร่)[<polite_suffix>]"
      - "[ตอนนี้]อากาศ[<here>]กี่องศา[<polite_suffix>]"
      - "[ตอนนี้]<here>ร้อนแค่ไหน[<polite_suffix>]"
      - "[ตอนนี้]<here>เย็นแค่ไหน[<polite_suffix>]"
      - "[ตอนนี้]<here>ร้อนไหม[<polite_suffix>]"
      - "[ตอนนี้]<here>เย็นไหม[<polite_suffix>]"
    example: "อุณหภูมิเท่าไหร่"
    response: "default"
