---
# HassMediaPrevious - default
# example: vorige
# context_area: true

language: "nl"
data:
  - sentences:
      - "[het|de] vorige [<media_item>]"
      - "(ga naar|zet) [het|de] vorige <media_item> [op]"
      - "ga [een] <media_item> terug"
      - "[de|het] vorige <media_item> (opzetten|afspelen)"
    example: "vorige"
    response: "default"
