---
# HassLawnMowerDock - default
# example: atura el tallagespa

language: "ca"
data:
  - sentences:
      - "(atura[r]|para[r]|<cancela>) [de ]tallar la gespa"
      - "(atura[r]|para[r]|<cancela>) [el] tallagespa"
      - "fes que [el] tallagespa ([re]torni|vagi) [a [la] base]"
    example: "atura el tallagespa"
    response: "default"
