language: "zh-HK"
data:
  - sentences:
      - "(設定|調整|調教|調|調高|調低)音量(為|到|至){volume:volume_level}[[ ]%| percent]"
      - "[把|將]音量(設定|調整|調教|調|調高|調低)(為|到|至){volume:volume_level}[[ ]%| percent]"
    example: "將音量調到50%"
    response: "default"
