---
# HassGetCurrentTime - default
# example: kolik je hodin

language: "cs"
data:
  - sentences:
      - "kolik je [přesně|[právě] teď] hodin"
      - "jaký je [přesný|[právě] teď] čas"
    example: "kolik je hodin"
    response: "default"
