---
# HassGetWeather - default
# example: jaké je počasí

language: "cs"
data:
  - sentences:
      - "jak[(ý|ej|á|é|ých|ejch|o)] ((je|jsou)|bud(e|ou)) počasí"
    example: "jaké je počasí"
    response: "default"
  - sentences:
      - "jaké je počasí"
    example: "jaké je počasí"
    response: "default"
    speech_to_phrase: true
