language: "fr"
data:
  - sentences:
      - "(réactive|rétablis|remets) [<le>] son [<ici>]"
      - "(désactive|enlève|supprime) la sourdine [<ici>]"
      - "(remets|remettre) [<le>]<volume> [<ici>]"
      - "remet le son [<ici>]"
    requires_context:
      area:
        slot: true
    response: "default"
