language: "fr"
data:
  - sentences:
      - "<reprends> [<le>] son [<ici>]"
      - "<reprends> [<le>]<volume> [<ici>]"
      - "<enleve> la sourdine [<ici>]"
    requires_context:
      area:
        slot: true
    response: "default"
