---
# HassMediaPause - default
# example: pausa
# context_area: true

language: "es"
data:
  - sentences:
      - "<pausa>"
      - "<pausa> [la |el |mi ](música|programa|vídeo|video|reproducción|reproductor)"
    example: "pausa"
    response: "default"
  - sentences:
      - "pausa"
      - "pausa la música"
    example: "pausa"
    response: "default"
    speech_to_phrase: true
