---
# HassGetCurrentTime - default
# example: कति बजी रहेको छ

language: "ne"
data:
  - sentences:
      - "[अहिले] कति बजी रहेको छ"
      - "कति बजी रहेको छ [अहिले]"
    example: "अहिले कति बजी रहेको छ"
    response: "default"
