---
# HassFanSetSpeed - default
# example: posa els ventiladors al 50%
# slots: {percentage}; context_area: true

language: "ca"
data:
  - sentences:
      - "<configura> la velocitat de(l|ls) ventilador[s] [d'aqu(i|í)] (a|al) <fan_speed>"
      - "<configura> [el|els] ventilador[s] [d'aqu(i|í)] (a|al) <fan_speed>"
    example: "posa els ventiladors al 50%"
    response: "default"
