---
# HassPauseTimer - default

language: "nl"
data:
  - sentences:
      - "pauzeer [<my>] <timer>"
      - "[<my>] <timer> (pauzeren|op pauze zetten)"
    example: "pauzeer timer"
    response: "default"
  - sentences:
      - "pauzeer de timer"
    example: "pauzeer de timer"
    response: "default"
    speech_to_phrase: true
