language: "nb"
data:
  - sentences:
      - "(hallo|hei) [home assistant]"
    example: "hei"
    response: "hello"

  - sentences:
      - "(lytter|hører) du alltid [etter|på] [meg|oss]"
    example: "lytter du alltid"
    response: "listening"

  - sentences:
      - "hvor (går|sendes) [min[e]] [data[ene]] [til|hen]"
      - "hvor (går|sendes) data[ene] [min[e]] [til|hen]"
    example: "hvor går dataene mine"
    response: "data"

  - sentences:
      - "hva kan jeg (si|spørre om)"
    example: "hva kan jeg si"
    response: "commands"

  - sentences:
      - "hvem [har] (lagd|skapt)[e] [deg]"
    example: "hvem lagde deg"
    response: "creator"
