language: "fr"
data:
  - sentences:
      - "<regle> [<le>]<ventilateur> [<ici>] [(à|sur)] {brightness:percentage}<pourcent>"
      - "<regle> [la] vitesse [<de>] [<le>]<ventilateur> [<ici>] [(à|sur)] {brightness:percentage}<pourcent>"
    requires_context:
      area:
        slot: true
    response: "default"
