---
# HassLawnMowerStartMowing - default
# example: mäh den Rasen

language: "de"
data:
  - sentences:
      - "(Starte|Schicke) den (Rasenmäher|Rasenroboter)"
      - "Schicke den (Rasenmäher|Rasenroboter) los"
      - "mäh[e] ([den ]Rasen|die Wiese)"
      - "[den ](Rasenmäher|Rasenroboter) (starten|[los[ ]]schicken)"
      - "([den ]Rasen|die Wiese) mähen"
    example: "mäh den Rasen"
    response: "default"
