---
# HassSetVolume - default
# example: poner volumen al 90 por ciento
# slots: {volume_level}
# context_area: true

language: "es"
data:
  - sentences:
      - "<establece_sube_baja> [el ]volumen a[l] {volume:volume_level} [<porciento>]"
    example: "poner volumen al 90 por ciento"
    response: "default"
