---
# HassSetVolume - default
# slots: {volume_level}; context_area: true

language: "nl"
data:
  - sentences:
      - "<numeric_value_set> [het] volume (naar|op) {volume:volume_level}[[ ]%|procent]"
      - "<numeric_value_set> [het] volume [omhoog|omlaag] (naar|op) {volume:volume_level}[[ ]%|procent]"
      - "({volume:volume_level}[[ ]%|procent];volume)"
    example: "zet het volume naar 90 procent"
    response: "default"
