---
# HassGetCurrentTime - default
# example: qué hora es

language: "es"
data:
  - sentences:
      - "[<dime> ]qué hora es[ ahora]"
      - "<dime> la hora[ actual]"
      - "<cual_es> hora"
      - "hora actual"
    example: "qué hora es"
    response: "default"
