language: el
data:
  - sentences:
      - επόμενο [(κομμάτι | τραγούδι)]
      - (πάμε στο επόμενο [(κομμάτι | τραγούδι)] | παράλειψε [(αυτό το κομμάτι | το τραγούδι)])
    example: επόμενο κομμάτι
    response: default
