---
# HassGetWeather - default
# example: jaka jest pogoda

language: "pl"
data:
  - sentences:
      - "Jak(a jest|ą [dzisiaj|teraz] mamy|ą mamy [dzisiaj|teraz]|a jest [dzisiaj|teraz]) (pogoda|pogodę)"
      - "Jakie są [dzisiaj |teraz ]warunki pogodowe"
    example: "jaka jest pogoda"
    response: "default"
