---
# HassMediaPrevious - default
# example: العنصر السابق
# context_area: true

language: "ar"
data:
  - sentences:
      - "(<go_back>|[المسار|العنصر] <previous>)"
      - "(<replay>|<go_back>|<go>) [<to>][المسار|الأغنية] (<previous>|<last>)"
    example: "العنصر السابق"
    response: "default"
