---
# HassClimateGetTemperature - default
# example: jaká je teplota
# context_area: true

language: "cs"
data:
  - sentences:
      - "jaká (je;[<tady>];teplota)"
      - "kolik (je;[<tady>];stupňů)"
      - "jak ((teplo|chladno);je;[<tady>])"
    example: "jaká je teplota"
    response: "default"
