---
# HassMediaSearchAndPlay - default
# example: joue Pink Floyd
# slots: {search_query}
# context_area: true

language: fr
data:
  - sentences:
      - "(<active>|<mets>|<ecoute>) [<de>] {search_query} [<ici>]"
      - "(<active>|<mets>|<ecoute>) [<le>]<media> [<de>] {search_query} [<ici>]"
    example: "joue Pink Floyd"
    response: "default"
