---
# HassRespond - default
# example: hello

language: "ar"
data:
  - sentences:
      - "<hello> [<home_assistant>]"
    example: "اهلا"
    response: "hello"
  - sentences:
      - "هل انت دائما ([ت]تسمع|تسجل)"
    example: "هل انت دائما تسمع"
    response: "listening"
  - sentences:
      - "<where> <go> (بياناتي|معلوماتي) [الخاصه]"
    example: "لوين تروح بياناتي"
    response: "data"
  - sentences:
      - "<what_is> <can> (اسال|اقول)"
    example: "شو ممكن اسال"
    response: "commands"
  - sentences:
      - "من [الذي[ن]] (صنع[و]ك|صمم[و]ك)"
    example: "من صنعك"
    response: "creator"
