---
# HassNevermind - default
# example: ei mitään

language: "fi"
data:
  - sentences:
      - "ei [sittenkään] mitään"
      - "unohda"
      - "peruuta"
      - "anna [sittenkin] olla"
    example: "ei mitään"
    response: "default"
