---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]

  pull_request:

permissions:
  contents: read

concurrency:
  # yamllint disable-line rule:line-length
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - run: script/setup
      - run: script/lint
      - run: venv/bin/python3 -m script.intentfest add_language test_add_language_generates_valid_tests
      - run: script/test
