---
# HassGetWeather - default
# example: цаг агаар ямар байна вэ

language: "mn"
data:
  - sentences:
      - "[одоо] [гадаа] цаг агаар ямар байна вэ"
      - "[гадаа] ([одоо] цаг агаар|[одоо] цаг агаарын төлөв) (хэр|ямархуу) байна вэ"
    example: "цаг агаар ямар байна вэ"
    response: "default"
