---
# HassGetWeather - default
# example: qué tiempo hace

language: "es"
data:
  - sentences:
      - "qué tiempo hace[ hoy| ahora]"
      - "cómo está el tiempo[ hoy| ahora]"
    example: "qué tiempo hace"
    response: "default"
  - sentences:
      - "qué tiempo hace"
    example: "qué tiempo hace"
    response: "default"
    speech_to_phrase: true
